name: Realm Dart for Windows

on:
  push:
    branches:
    # Do not run if change is in these paths
    paths-ignore:
      - 'flutter/**'
      - 'generator/**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+**' # matches tags like number(s).number(s).number(s)(any) for ex: 1.0.0 and also 1.0.0+beta
  pull_request:
    # Do not run if change is in these paths
    paths-ignore:
        - 'flutter/**'
        - 'generator/**'

jobs:
  CI:
    runs-on: windows-2019
    env:
      REALM_CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build Realm Dart for Windows
        run: scripts\build.bat

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - name : Setup Dart SDK
        uses: dart-lang/setup-dart@main

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: |
          dart test -r expanded
          echo "archive_file_path=%CD%/binary/windows.tar.gz" >> $GITHUB_ENV
          echo "source_path=%CD%/binary/windows" >> $GITHUB_ENV

      - name: Release artifacts
        if: ${{ success() && github.event_name == 'push' && github.ref_type == 'tag' }}
        uses: ./.github/workflows/release-artifacts.yaml
        with:
          package_name: realm_dart
          source_path: $source_path
          archive_file_path: $archive_file_path
