name: Release Realm artifacts

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      source_path:
        required: true
        type: string
      archive_file_path:
        required: true
        type: string

jobs:
  - name: Archive binary
    if: ${{ success() && github.event_name == 'push' && github.ref_type == 'tag' }}
    run: |
      dart run ${{ inputs.package_name }} archive --source-dir ${{ inputs.source_path }} --output-file ${{ inputs.archive_file_path }}

  - name: Release artifacts
    if: ${{ success() && github.event_name == 'push' && github.ref_type == 'tag' }}
    uses: ncipollo/release-action@v1
    with:
      allowUpdates:  true
      artifactErrorsFailBuild: true
      draft: true
      omitNameDuringUpdate: true
      prerelease: false
      omitPrereleaseDuringUpdate: true
      artifacts: ${{ inputs.archive_file_path }}
      body: "ADD RELEASE NOTES"
      omitBodyDuringUpdate: true
      token: ${{ secrets.GITHUB_TOKEN }}